name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: make build

    - name: Create secrete SSH key
      run: touch ~/.ssh/id_ed25519

    - name: Set secret data to SSH key
      run: echo ${{ secrets.DATA }} >> ~/.ssh/id_ed25519

    - name: Test
      run: make test
