name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: make build

    - name: Create directory for SSH keys
      run: mkdir ~/.ssh

    - name: Create private SSH key file
      run: touch ~/.ssh/id_ed25519

    - name: Create public SSH key file
      run: touch ~/.ssh/id_ed25519.pub

    - name: Set secret data to public SSH key
      run: 'echo "$DATA" > ~/.ssh/id_ed25519.pub'
      shell: bash
      env:
        DATA: ${{secrets.DATA}}

    - name: Set secret data to private SSH key
      run: 'echo "$TOKEN" > ~/.ssh/id_ed25519'
      shell: bash
      env:
        DATA: ${{secrets.TOKEN}}

    - name: Test
      run: make test
